---
config:
  layout: elk
  elk:
    mergeEdges: false
    nodePlacementStrategy: NETWORK_SIMPLEX
---
flowchart LR
  classDef default stroke:#333,stroke-width:1px,font-size:14px;
  classDef technology fill:#9c9,font-size:16px,font-weight:bold;
  classDef building fill:#ccc;
  classDef wonder fill:#cc9;
  classDef unit fill:#99c;
  classDef spaceshippart fill:#c99;

  %% Technologies
  AdvancedFlightTech("Advanced Flight")
  class AdvancedFlightTech technology
  AlphabetTech("Alphabet")
  class AlphabetTech technology
  AstronomyTech("Astronomy")
  class AstronomyTech technology
  AtomicTheoryTech("Atomic Theory")
  class AtomicTheoryTech technology
  AutomobileTech("Automobile")
  class AutomobileTech technology
  BankingTech("Banking")
  class BankingTech technology
  BridgeBuildingTech("Bridge Building")
  class BridgeBuildingTech technology
  BronzeWorkingTech("Bronze Working")
  class BronzeWorkingTech technology
  CeremonialBurialTech("Ceremonial Burial")
  class CeremonialBurialTech technology
  ChemistryTech("Chemistry")
  class ChemistryTech technology
  ChivalryTech("Chivalry")
  class ChivalryTech technology
  CodeOfLawsTech("Code of Laws")
  class CodeOfLawsTech technology
  CombustionTech("Combustion")
  class CombustionTech technology
  CommunismTech("Communism")
  class CommunismTech technology
  ComputersTech("Computers")
  class ComputersTech technology
  ConscriptionTech("Conscription")
  class ConscriptionTech technology
  ConstructionTech("Construction")
  class ConstructionTech technology
  CurrencyTech("Currency")
  class CurrencyTech technology
  DemocracyTech("Democracy")
  class DemocracyTech technology
  ElectricityTech("Electricity")
  class ElectricityTech technology
  ElectronicsTech("Electronics")
  class ElectronicsTech technology
  EngineeringTech("Engineering")
  class EngineeringTech technology
  ExplosivesTech("Explosives")
  class ExplosivesTech technology
  FeudalismTech("Feudalism")
  class FeudalismTech technology
  FlightTech("Flight")
  class FlightTech technology
  FusionPowerTech("Fusion Power")
  class FusionPowerTech technology
  GeneticEngineeringTech("Genetic Engineering")
  class GeneticEngineeringTech technology
  GunpowderTech("Gunpowder")
  class GunpowderTech technology
  HorsebackRidingTech("Horseback Riding")
  class HorsebackRidingTech technology
  IndustrializationTech("Industrialization")
  class IndustrializationTech technology
  InventionTech("Invention")
  class InventionTech technology
  IronWorkingTech("Iron Working")
  class IronWorkingTech technology
  LaborUnionTech("Labor Union")
  class LaborUnionTech technology
  LiteracyTech("Literacy")
  class LiteracyTech technology
  MagnetismTech("Magnetism")
  class MagnetismTech technology
  MapMakingTech("Map Making")
  class MapMakingTech technology
  MasonryTech("Masonry")
  class MasonryTech technology
  MassProductionTech("Mass Production")
  class MassProductionTech technology
  MathematicsTech("Mathematics")
  class MathematicsTech technology
  MedicineTech("Medicine")
  class MedicineTech technology
  MetallurgyTech("Metallurgy")
  class MetallurgyTech technology
  MonarchyTech("Monarchy")
  class MonarchyTech technology
  MysticismTech("Mysticism")
  class MysticismTech technology
  NavigationTech("Navigation")
  class NavigationTech technology
  NuclearFissionTech("Nuclear Fission")
  class NuclearFissionTech technology
  NuclearPowerTech("Nuclear Power")
  class NuclearPowerTech technology
  PhilosophyTech("Philosophy")
  class PhilosophyTech technology
  PhysicsTech("Physics")
  class PhysicsTech technology
  PlasticsTech("Plastics")
  class PlasticsTech technology
  PotteryTech("Pottery")
  class PotteryTech technology
  RailroadTech("Railroad")
  class RailroadTech technology
  RecyclingTech("Recycling")
  class RecyclingTech technology
  RefiningTech("Refining")
  class RefiningTech technology
  ReligionTech("Religion")
  class ReligionTech technology
  RoboticsTech("Robotics")
  class RoboticsTech technology
  RocketryTech("Rocketry")
  class RocketryTech technology
  SpaceFlightTech("Space Flight")
  class SpaceFlightTech technology
  SteamEngineTech("Steam Engine")
  class SteamEngineTech technology
  SteelTech("Steel")
  class SteelTech technology
  SuperConductorTech("Super Conductor")
  class SuperConductorTech technology
  TheCorporationTech("The Corporation")
  class TheCorporationTech technology
  TheRepublicTech("The Republic")
  class TheRepublicTech technology
  TheWheelTech("The Wheel")
  class TheWheelTech technology
  TheoryOfGravityTech("Theory of Gravity")
  class TheoryOfGravityTech technology
  TradeTech("Trade")
  class TradeTech technology
  UniversityTech("University")
  class UniversityTech technology
  WritingTech("Writing")
  class WritingTech technology

  %% Buildings
  AqueductBuilding("Aqueduct")
  class AqueductBuilding building
  BankBuilding("Bank")
  class BankBuilding building
  CathedralBuilding("Cathedral")
  class CathedralBuilding building
  CityWallsBuilding("City Walls")
  class CityWallsBuilding building
  ColosseumBuilding("Colosseum")
  class ColosseumBuilding building
  CourthouseBuilding("Courthouse")
  class CourthouseBuilding building
  FactoryBuilding("Factory")
  class FactoryBuilding building
  GranaryBuilding("Granary")
  class GranaryBuilding building
  HydroPlantBuilding("Hydro Plant")
  class HydroPlantBuilding building
  LibraryBuilding("Library")
  class LibraryBuilding building
  MarketplaceBuilding("Marketplace")
  class MarketplaceBuilding building
  MassTransitBuilding("Mass Transit")
  class MassTransitBuilding building
  MfgPlantBuilding("Manufacturing Plant")
  class MfgPlantBuilding building
  NuclearPlantBuilding("Nuclear Plant")
  class NuclearPlantBuilding building
  PalaceBuilding("Palace")
  class PalaceBuilding building
  PowerPlantBuilding("Power Plant")
  class PowerPlantBuilding building
  RecyclingCenterBuilding("Recycling Center")
  class RecyclingCenterBuilding building
  SDIDefenseBuilding("SDI Defense")
  class SDIDefenseBuilding building
  TempleBuilding("Temple")
  class TempleBuilding building
  UniversityBuilding("University")
  class UniversityBuilding building

  %% Wonders
  ApolloProgramWonder("Apollo Program")
  class ApolloProgramWonder wonder
  ColossusWonder("Colossus")
  class ColossusWonder wonder
  CopernicusObservatoryWonder("Copernicus' Observatory")
  class CopernicusObservatoryWonder wonder
  CureForCancerWonder("Cure for Cancer")
  class CureForCancerWonder wonder
  DarwinsVoyageWonder("Darwin's Voyage")
  class DarwinsVoyageWonder wonder
  GreatLibraryWonder("Great Library")
  class GreatLibraryWonder wonder
  GreatWallWonder("Great Wall")
  class GreatWallWonder wonder
  HangingGardensWonder("Hanging Gardens")
  class HangingGardensWonder wonder
  HooverDamWonder("Hoover Dam")
  class HooverDamWonder wonder
  IsaacNewtonsCollegeWonder("Isaac Newton's College")
  class IsaacNewtonsCollegeWonder wonder
  JSBachsCathedralWonder("JS Bach's Cathedral")
  class JSBachsCathedralWonder wonder
  LighthouseWonder("Lighthouse")
  class LighthouseWonder wonder
  MagellansExpeditionWonder("Magellan's Expedition")
  class MagellansExpeditionWonder wonder
  ManhattanProjectWonder("Manhattan Project")
  class ManhattanProjectWonder wonder
  MichelangelosChapelWonder("Michelangelo's Chapel")
  class MichelangelosChapelWonder wonder
  OracleWonder("Oracle")
  class OracleWonder wonder
  PyramidsWonder("Pyramids")
  class PyramidsWonder wonder
  SETIProgramWonder("SETI Program")
  class SETIProgramWonder wonder
  ShakespearesTheaterWonder("Shakespeare's Theater")
  class ShakespearesTheaterWonder wonder
  UnitedNationsWonder("United Nations")
  class UnitedNationsWonder wonder
  WomensSuffrageWonder("Women's Suffrage")
  class WomensSuffrageWonder wonder

  %% Units
  ArmorUnit("Armor Unit")
  class ArmorUnit unit
  ArtilleryUnit("Artillery Unit")
  class ArtilleryUnit unit
  BattleshipUnit("Battleship Unit")
  class BattleshipUnit unit
  BomberUnit("Bomber Unit")
  class BomberUnit unit
  CannonUnit("Cannon Unit")
  class CannonUnit unit
  CaravanUnit("Caravan Unit")
  class CaravanUnit unit
  CarrierUnit("Carrier Unit")
  class CarrierUnit unit
  CatapultUnit("Catapult Unit")
  class CatapultUnit unit
  CavalryUnit("Cavalry Unit")
  class CavalryUnit unit
  ChariotUnit("Chariot Unit")
  class ChariotUnit unit
  CruiserUnit("Cruiser Unit")
  class CruiserUnit unit
  DiplomatUnit("Diplomat Unit")
  class DiplomatUnit unit
  FighterUnit("Fighter Unit")
  class FighterUnit unit
  FortressUnit("Fortress Unit")
  class FortressUnit unit
  FrigateUnit("Frigate Unit")
  class FrigateUnit unit
  IroncladUnit("Ironclad Unit")
  class IroncladUnit unit
  KnightUnit("Knight Unit")
  class KnightUnit unit
  LegionUnit("Legion Unit")
  class LegionUnit unit
  MechInfantryUnit("Mech Infantry Unit")
  class MechInfantryUnit unit
  MusketeersUnit("Musketeers Unit")
  class MusketeersUnit unit
  NuclearUnit("Nuclear Unit")
  class NuclearUnit unit
  PhalanxUnit("Phalanx Unit")
  class PhalanxUnit unit
  RiflemenUnit("Riflemen Unit")
  class RiflemenUnit unit
  SailUnit("Sail Unit")
  class SailUnit unit
  SubmarineUnit("Submarine Unit")
  class SubmarineUnit unit
  TransportUnit("Transport Unit")
  class TransportUnit unit
  TriremeUnit("Trireme Unit")
  class TriremeUnit unit

  %% Spaceship Parts
  SSStructure("SS Structure")
  class SSStructure spaceshippart
  SSComponent("SS Component")
  class SSComponent spaceshippart
  SSModule("SS Module")
  class SSModule spaceshippart

  %% Technology Dependencies
  ElectricityTech==>AdvancedFlightTech
  FlightTech==>AdvancedFlightTech
  MathematicsTech==>AstronomyTech
  MysticismTech==>AstronomyTech
  PhysicsTech==>AtomicTheoryTech
  TheoryOfGravityTech==>AtomicTheoryTech
  SteelTech==>AutomobileTech
  CombustionTech==>AutomobileTech
  TheRepublicTech==>BankingTech
  TradeTech==>BankingTech
  ConstructionTech==>BridgeBuildingTech
  IronWorkingTech==>BridgeBuildingTech
  MedicineTech==>ChemistryTech
  UniversityTech==>ChemistryTech
  FeudalismTech==>ChivalryTech
  HorsebackRidingTech==>ChivalryTech
  AlphabetTech==>CodeOfLawsTech
  RefiningTech==>CombustionTech
  ExplosivesTech==>CombustionTech
  IndustrializationTech==>CommunismTech
  PhilosophyTech==>CommunismTech
  ElectronicsTech==>ComputersTech
  MathematicsTech==>ComputersTech
  ExplosivesTech==>ConscriptionTech
  TheRepublicTech==>ConscriptionTech
  CurrencyTech==>ConstructionTech
  MasonryTech==>ConstructionTech
  BronzeWorkingTech==>CurrencyTech
  LiteracyTech==>DemocracyTech
  PhilosophyTech==>DemocracyTech
  MagnetismTech==>ElectricityTech
  MetallurgyTech==>ElectricityTech
  ElectricityTech==>ElectronicsTech
  EngineeringTech==>ElectronicsTech
  ConstructionTech==>EngineeringTech
  TheWheelTech==>EngineeringTech
  ChemistryTech==>ExplosivesTech
  GunpowderTech==>ExplosivesTech
  MasonryTech==>FeudalismTech
  MonarchyTech==>FeudalismTech
  PhysicsTech==>FlightTech
  CombustionTech==>FlightTech
  NuclearPowerTech==>FusionPowerTech
  SuperConductorTech==>FusionPowerTech
  MedicineTech==>GeneticEngineeringTech
  TheCorporationTech==>GeneticEngineeringTech
  InventionTech==>GunpowderTech
  IronWorkingTech==>GunpowderTech
  BankingTech==>IndustrializationTech
  RailroadTech==>IndustrializationTech
  EngineeringTech==>InventionTech
  LiteracyTech==>InventionTech
  BronzeWorkingTech==>IronWorkingTech
  CommunismTech==>LaborUnionTech
  MassProductionTech==>LaborUnionTech
  CodeOfLawsTech==>LiteracyTech
  WritingTech==>LiteracyTech
  PhysicsTech==>MagnetismTech
  NavigationTech==>MagnetismTech
  AlphabetTech==>MapMakingTech
  AutomobileTech==>MassProductionTech
  TheCorporationTech==>MassProductionTech
  AlphabetTech==>MathematicsTech
  WritingTech==>MathematicsTech
  PhilosophyTech==>MedicineTech
  TradeTech==>MedicineTech
  GunpowderTech==>MetallurgyTech
  UniversityTech==>MetallurgyTech
  CodeOfLawsTech==>MonarchyTech
  CeremonialBurialTech==>MonarchyTech
  CeremonialBurialTech==>MysticismTech
  AstronomyTech==>NavigationTech
  MapMakingTech==>NavigationTech
  AtomicTheoryTech==>NuclearFissionTech
  MassProductionTech==>NuclearFissionTech
  NuclearFissionTech==>NuclearPowerTech
  ElectronicsTech==>NuclearPowerTech
  LiteracyTech==>PhilosophyTech
  MysticismTech==>PhilosophyTech
  MathematicsTech==>PhysicsTech
  NavigationTech==>PhysicsTech
  SpaceFlightTech==>PlasticsTech
  RefiningTech==>PlasticsTech
  BridgeBuildingTech==>RailroadTech
  SteamEngineTech==>RailroadTech
  DemocracyTech==>RecyclingTech
  MassProductionTech==>RecyclingTech
  ChemistryTech==>RefiningTech
  TheCorporationTech==>RefiningTech
  PhilosophyTech==>ReligionTech
  WritingTech==>ReligionTech
  ComputersTech==>RoboticsTech
  PlasticsTech==>RoboticsTech
  AdvancedFlightTech==>RocketryTech
  ElectronicsTech==>RocketryTech
  RocketryTech==>SpaceFlightTech
  NuclearFissionTech==>SpaceFlightTech
  InventionTech==>SteamEngineTech
  PhysicsTech==>SteamEngineTech
  IndustrializationTech==>SteelTech
  MetallurgyTech==>SteelTech
  PlasticsTech==>SuperConductorTech
  MassProductionTech==>SuperConductorTech
  BankingTech==>TheCorporationTech
  IndustrializationTech==>TheCorporationTech
  CodeOfLawsTech==>TheRepublicTech
  LiteracyTech==>TheRepublicTech
  AstronomyTech==>TheoryOfGravityTech
  UniversityTech==>TheoryOfGravityTech
  CodeOfLawsTech==>TradeTech
  CurrencyTech==>TradeTech
  MathematicsTech==>UniversityTech
  PhilosophyTech==>UniversityTech
  AlphabetTech==>WritingTech

  %% Building Dependencies
  CeremonialBurialTech-->TempleBuilding
  PotteryTech-->GranaryBuilding
  MasonryTech-->PalaceBuilding
  MasonryTech-->CityWallsBuilding
  CodeOfLawsTech-->CourthouseBuilding
  WritingTech-->LibraryBuilding
  ConstructionTech-->AqueductBuilding
  ConstructionTech-->ColosseumBuilding
  CurrencyTech-->MarketplaceBuilding
  BankingTech-->BankBuilding
  UniversityTech-->UniversityBuilding
  ReligionTech-->CathedralBuilding
  IndustrializationTech-->FactoryBuilding
  ElectronicsTech-->HydroPlantBuilding
  RefiningTech-->PowerPlantBuilding
  MassProductionTech-->MassTransitBuilding
  RoboticsTech-->MfgPlantBuilding
  SuperConductorTech-->SDIDefenseBuilding
  RecyclingTech-->RecyclingCenterBuilding
  NuclearPowerTech-->NuclearPlantBuilding

  %% Wonder Dependencies
  PotteryTech-.->HangingGardensWonder
  MasonryTech-.->PyramidsWonder
  MasonryTech-.->GreatWallWonder
  BronzeWorkingTech-.->ColossusWonder
  MysticismTech-.->OracleWonder
  MapMakingTech-.->LighthouseWonder
  AstronomyTech-.->CopernicusObservatoryWonder
  LiteracyTech-.->GreatLibraryWonder
  NavigationTech-.->MagellansExpeditionWonder
  RailroadTech-.->DarwinsVoyageWonder
  MedicineTech-.->ShakespearesTheaterWonder
  ReligionTech-.->JSBachsCathedralWonder
  ReligionTech-.->MichelangelosChapelWonder
  TheoryOfGravityTech-.->IsaacNewtonsCollegeWonder
  IndustrializationTech-.->WomensSuffrageWonder
  ElectronicsTech-.->HooverDamWonder
  CommunismTech-.->UnitedNationsWonder
  ComputersTech-.->SETIProgramWonder
  GeneticEngineeringTech-.->CureForCancerWonder
  SpaceFlightTech-.->ApolloProgramWonder
  NuclearFissionTech-.->ManhattanProjectWonder

  %% Unit Dependencies
  HorsebackRidingTech-->CavalryUnit
  TheWheelTech-->ChariotUnit
  BronzeWorkingTech-->PhalanxUnit
  ChivalryTech-->KnightUnit
  MapMakingTech-->TriremeUnit
  WritingTech-->DiplomatUnit
  ConstructionTech-->FortressUnit
  IronWorkingTech-->LegionUnit
  MathematicsTech-->CatapultUnit
  TradeTech-->CaravanUnit
  NavigationTech-->SailUnit
  MagnetismTech-->FrigateUnit
  SteamEngineTech-->IroncladUnit
  GunpowderTech-->MusketeersUnit
  FlightTech-->FighterUnit
  IndustrializationTech-->TransportUnit
  MetallurgyTech-->CannonUnit
  AdvancedFlightTech-->BomberUnit
  AdvancedFlightTech-->CarrierUnit
  SteelTech-->BattleshipUnit
  ConscriptionTech-->RiflemenUnit
  RocketryTech-->NuclearUnit
  LaborUnionTech-->MechInfantryUnit
  AutomobileTech-->ArmorUnit
  CombustionTech-->CruiserUnit
  MassProductionTech-->SubmarineUnit
  RoboticsTech-->ArtilleryUnit

  %% Spaceship Part Dependencies
  SpaceFlightTech-.->SSStructure
  PlasticsTech-.->SSComponent
  RoboticsTech-.->SSModule
